{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from OCC.Core.gp import gp_Pnt\n",
    "from OCC.Core.Geom import Geom_BezierSurface, Geom_BSplineSurface, Geom_BezierCurve, Geom_BSplineCurve, Geom_Circle \n",
    "from OCC.Core.TColgp import TColgp_Array2OfPnt\n",
    "from OCC.Core.TColStd import TColStd_Array1OfReal, TColStd_Array1OfInteger\n",
    "from OCC.Core.ShapeAnalysis import ShapeAnalysis_FreeBounds\n",
    "from OCC.Core.TopTools import TopTools_HSequenceOfShape\n",
    "import json\n",
    "import numpy as np\n",
    "\n",
    "from OCC.Core.gp import gp_Pnt, gp_Dir, gp_Ax2, gp_Vec, gp_Circ, gp_Lin, gp_Ax1, gp_Ax3, gp_Elips, gp_Hypr, gp_Parab, gp_Pln, gp_Cylinder, gp_Cone, gp_Sphere, gp_Torus, gp_Trsf\n",
    "from OCC.Core.Geom import Geom_Circle, Geom_Line, Geom_BSplineCurve, Geom_TrimmedCurve, Geom_Ellipse, Geom_Hyperbola, Geom_Parabola, Geom_Plane, Geom_CylindricalSurface, Geom_ConicalSurface, Geom_SphericalSurface\n",
    "from OCC.Core.GC import GC_MakeArcOfCircle, GC_MakeSegment, GC_MakeArcOfEllipse, GC_MakeArcOfHyperbola, GC_MakeArcOfParabola\n",
    "from OCC.Core.BRepBuilderAPI import BRepBuilderAPI_MakeEdge, BRepBuilderAPI_MakeWire, BRepBuilderAPI_MakeFace ,BRepBuilderAPI_DisconnectedWire, BRepBuilderAPI_EmptyWire, BRepBuilderAPI_NonManifoldWire, BRepBuilderAPI_WireDone, BRepBuilderAPI_Transform\n",
    "from OCC.Core.TopoDS import TopoDS_Edge\n",
    "from OCC.Core.TopLoc import TopLoc_Location\n",
    "from OCC.Core.Poly import Poly_Triangulation\n",
    "from OCC.Core.TColgp import TColgp_Array1OfPnt\n",
    "from OCC.Core.TColStd import TColStd_Array1OfReal, TColStd_Array1OfInteger\n",
    "from OCC.Core.GeomAPI import GeomAPI_ProjectPointOnCurve\n",
    "from OCC.Core.BRep import BRep_Tool\n",
    "from OCC.Core.BRepMesh import BRepMesh_IncrementalMesh\n",
    "from OCC.Display.SimpleGui import init_display\n",
    "from OCC.Core.BRepLib import breplib\n",
    "from OCC.Core.ShapeFix import ShapeFix_Shape, ShapeFix_Wire, ShapeFix_Edge\n",
    "from OCC.Core.ShapeExtend import ShapeExtend_DONE1\n",
    "from OCC.Core.BRepCheck import BRepCheck_Analyzer\n",
    "from OCC.Core.BRepOffsetAPI import BRepOffsetAPI_ThruSections\n",
    "from OCC.Core.ShapeAnalysis import ShapeAnalysis_Wire\n",
    "from OCC.Core.TopAbs import TopAbs_Orientation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "ename": "TypeError",
     "evalue": "'type' object is not subscriptable",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp\\ipykernel_13224\\2660306116.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[1;32m----> 1\u001b[1;33m \u001b[1;32mfrom\u001b[0m \u001b[0mfreecad_visualize_json_pythonocc\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0m_build_and_mesh_face_robustly_from_topods\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mextract_mesh_from_face\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      2\u001b[0m \u001b[1;32mfrom\u001b[0m \u001b[0mitertools\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mcombinations\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mf:\\WORK\\CAD\\CLR-Wire\\freecad_visualize_json_pythonocc.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m    592\u001b[0m \u001b[1;32mfrom\u001b[0m \u001b[0mOCC\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mCore\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mTopoDS\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mTopoDS_Wire\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    593\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 594\u001b[1;33m \u001b[1;32mdef\u001b[0m \u001b[0msample_wire_by_distance\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mwire\u001b[0m\u001b[1;33m:\u001b[0m \u001b[0mTopoDS_Wire\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mdistance\u001b[0m\u001b[1;33m:\u001b[0m \u001b[0mfloat\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;33m->\u001b[0m \u001b[0mlist\u001b[0m\u001b[1;33m[\u001b[0m\u001b[0mgp_Pnt\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    595\u001b[0m     \"\"\"\n\u001b[0;32m    596\u001b[0m     \u001b[1;33m[\u001b[0m\u001b[0m修正版\u001b[0m\u001b[1;33m]\u001b[0m \u001b[0m通过在Wire上按大致固定的空间距离来采样点\u001b[0m\u001b[0;31m。\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mTypeError\u001b[0m: 'type' object is not subscriptable"
     ]
    }
   ],
   "source": [
    "from freecad_visualize_json_pythonocc import _build_and_mesh_face_robustly_from_topods, extract_mesh_from_face\n",
    "from itertools import combinations"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def build_second_order_surface(face):\n",
    "    surface_type = face['surface_type']\n",
    "    parameter_range = face['parameter_range']\n",
    "    u_min, u_max, v_min, v_max = parameter_range\n",
    "    position = np.array(face['surface_definition']['position'])\n",
    "    axis = np.array(face['surface_definition']['axis'])\n",
    "    orientation = face['orientation']\n",
    "    # 归一化参数范围\n",
    "    if surface_type == 'Cylinder' or surface_type == 'Cone':\n",
    "        position = position + axis * v_min\n",
    "        v_max = v_max - v_min\n",
    "        v_min = 0\n",
    "    elif surface_type == 'Toriod':\n",
    "        position = position + axis * u_min\n",
    "        u_max = u_max - u_min\n",
    "        u_min = 0\n",
    "    print(position, axis, v_min, v_max)\n",
    "    if surface_type == 'Cylinder':\n",
    "        radius = face['surface_definition']['radius']\n",
    "    elif surface_type == 'Cone':\n",
    "        radius = face['surface_definition']['radius']\n",
    "        semi_angle = face['surface_definition']['semi_angle']\n",
    "    elif surface_type == 'Toroid':\n",
    "        major_radius = face['surface_definition']['major_radius']\n",
    "        minor_radius = face['surface_definition']['minor_radius']\n",
    "    else:\n",
    "        raise ValueError(f\"Surface type {surface_type} not supported\")\n",
    "    \n",
    "    occ_position = gp_Pnt(position[0], position[1], position[2])\n",
    "    occ_axis_dir = gp_Dir(axis[0], axis[1], axis[2])\n",
    "    \n",
    "    # 2. 创建定义圆柱位置和方向的坐标系\n",
    "    cylinder_ax3 = gp_Ax3(occ_position, occ_axis_dir)\n",
    "    if surface_type == 'Cylinder':\n",
    "        occ_surface = gp_Cylinder(cylinder_ax3, radius)\n",
    "    elif surface_type == 'Cone':\n",
    "        occ_surface = gp_Cone(cylinder_ax3, semi_angle, radius)\n",
    "    elif surface_type == 'Toroid':\n",
    "        occ_surface = gp_Torus(cylinder_ax3, major_radius, minor_radius)\n",
    "    # 4. 使用BRepBuilderAPI_MakeFace根据参数范围裁剪几何体，生成面\n",
    "    #    这是与C++ API最直接的对应\n",
    "    face_builder = BRepBuilderAPI_MakeFace(occ_surface, u_min, u_max, v_min, v_max)\n",
    "    # return face_builder.Face()\n",
    "    rotation_axis = np.array(face['rotation_axis'])\n",
    "    rotation_angle = face['rotation_angle']\n",
    "    occ_rotation_axis = gp_Dir(rotation_axis[0], rotation_axis[1], rotation_axis[2])\n",
    "    occ_rotation_center = occ_position\n",
    "    rotation_axis = gp_Ax1(occ_rotation_center, occ_rotation_axis)\n",
    "    trsf = gp_Trsf()\n",
    "    # if surface_type == 'Cylinder' or surface_type == 'Cone':\n",
    "    #     trsf.SetRotation(rotation_axis, 0)\n",
    "    # elif surface_type == 'Toroid':\n",
    "    trsf.SetRotation(rotation_axis, rotation_angle) # Bug: set rotation angle to 0\n",
    "    transformer = BRepBuilderAPI_Transform(face_builder.Shape(), trsf)\n",
    "    # print(type(transformer.Shape()))\n",
    "    shape = transformer.Shape()\n",
    "    mesher = BRepMesh_IncrementalMesh(shape, 0.1, True, 0.2)\n",
    "    mesher.Perform() # 确保执行网格化\n",
    "\n",
    "    if not mesher.IsDone():\n",
    "         print(\"警告: BRepMesh_IncrementalMesh 执行后报告未完成，网格可能无效。\")\n",
    "\n",
    "    # --- 步骤 D: 提取网格数据 ---\n",
    "    # 从修复并网格化后的面中提取数据\n",
    "    vertices, faces = extract_mesh_from_face(shape)\n",
    "    vertices = np.array(vertices)\n",
    "    faces = np.array(faces)\n",
    "    print(vertices.max(axis=0), vertices.min(axis=0))\n",
    "    return shape, vertices, faces"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
